import type { Metadata } from "next";
import { Fraunces, Hanken_Grotesk } from "next/font/google";
import "./globals.css";

// Display serif — old-style, high-contrast, characterful. Carries the
// heritage + precision of a long-established chartered accountancy.
const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700", "900"],
  style: ["normal", "italic"],
});

// Body / UI grotesque — clean and legible without reading as a startup default.
const hanken = Hanken_Grotesk({
  variable: "--font-hanken",
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "600", "700"],
});

const SITE_URL = "https://www.raeeskadiwal.com";
const SITE_NAME = "Raees Kadiwal & Co.";
const DESCRIPTION =
  "Raees Kadiwal & Co. — Trusted Chartered Accountant (CA) firm in Malad East, Mumbai with 17+ years of expertise. Expert in ITR filing, GST registration & compliance, company registration, statutory audit, TDS filing, NRI taxation, and financial advisory. Serving Pan-India clients from Mumbai – 400097.";

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),

  title: {
    default: `${SITE_NAME} | Chartered Accountant in Malad East, Mumbai`,
    template: `%s | ${SITE_NAME}`,
  },

  description: DESCRIPTION,

  keywords: [
    // Primary — firm & location
    "Raees Kadiwal & Co",
    "Raees Kadiwal Chartered Accountant",
    "Chartered Accountant Malad East Mumbai",
    "CA firm Malad East",
    "CA in Malad East Mumbai",
    "Chartered Accountant Malad Mumbai",
    "CA near Noorani Masjid Mumbai",
    "CA near Pathanwadi Malad",
    "CA Rani Sati Marg Malad",
    "CA firm Mumbai 400097",
    // Services — income tax
    "ITR filing Malad Mumbai",
    "income tax return filing Mumbai",
    "income tax consultant Malad East",
    "income tax notice handling Mumbai",
    "tax planning advisory Mumbai",
    "personal tax filing Mumbai",
    "salary ITR filing India",
    // Services — GST
    "GST registration Mumbai",
    "GST filing Malad Mumbai",
    "GST consultant Malad East",
    "GST returns compliance Mumbai",
    "GST audit Mumbai",
    "GST notice handling Mumbai",
    // Services — company / business
    "company registration Mumbai",
    "private limited company registration Mumbai",
    "OPC registration Mumbai",
    "LLP registration Mumbai",
    "startup advisory Mumbai",
    "MSME registration Mumbai",
    // Services — audit & accounting
    "statutory audit Mumbai",
    "internal audit Mumbai",
    "bookkeeping services Malad Mumbai",
    "accounting services Mumbai",
    "TDS filing Mumbai",
    "ROC compliance Mumbai",
    // Services — NRI
    "NRI taxation Mumbai",
    "NRI CA Mumbai",
    "NRI tax filing India",
    "NRI ITR filing Mumbai",
    // Generic long-tail
    "best CA in Mumbai",
    "top chartered accountant Mumbai",
    "CA near me Mumbai",
    "affordable CA services Mumbai",
    "CA for small business Mumbai",
  ],

  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,

  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },

  alternates: {
    canonical: SITE_URL,
  },

  openGraph: {
    type: "website",
    url: SITE_URL,
    locale: "en_IN",
    siteName: SITE_NAME,
    title: `${SITE_NAME} | Chartered Accountant in Malad East, Mumbai`,
    description:
      "17+ years of CA expertise in ITR, GST, Audit, Company Registration & Financial Advisory. Serving clients across Mumbai and Pan-India from Malad East, Mumbai – 400097.",
    // The social card image is generated by app/opengraph-image.tsx.
  },

  twitter: {
    card: "summary_large_image",
    site: "@raeeskadiwal",
    creator: "@raeeskadiwal",
    title: `${SITE_NAME} | CA in Malad East, Mumbai`,
    description:
      "Expert CA services — ITR, GST, Audit, Company Registration & more. 17+ years of trust. Malad East, Mumbai – 400097.",
    // The Twitter card image is generated by app/twitter-image.tsx.
  },

  category: "Financial Services",

  verification: {
    google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
  },
};

const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": ["AccountingService", "ProfessionalService", "LocalBusiness"],
      "@id": `${SITE_URL}/#business`,
      name: SITE_NAME,
      alternateName: ["Raees Kadiwal & Co", "Raees Kadiwal Chartered Accountants", "CA Raees Kadiwal"],
      url: SITE_URL,
      logo: {
        "@type": "ImageObject",
        url: `${SITE_URL}/ca-india-logo.png`,
      },
      image: `${SITE_URL}/opengraph-image`,
      description: DESCRIPTION,
      foundingDate: "2007",
      slogan: "17+ Years of Trusted CA Excellence",
      address: {
        "@type": "PostalAddress",
        streetAddress: "Shop No. 10, Fatima Tower, Near Noorani Masjid, Pathanwadi, Rani Sati Marg",
        addressLocality: "Malad East",
        addressRegion: "Maharashtra",
        postalCode: "400097",
        addressCountry: "IN",
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: "19.1791743",
        longitude: "72.8616513",
      },
      telephone: ["+919833771177", "+919967839778"],
      email: "raeesrahim@gmail.com",
      openingHoursSpecification: [
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          opens: "09:00",
          closes: "19:00",
        },
        {
          "@type": "OpeningHoursSpecification",
          dayOfWeek: "Sunday",
          opens: "10:00",
          closes: "14:00",
          description: "By Appointment Only",
        },
      ],
      areaServed: [
        { "@type": "City", name: "Mumbai" },
        { "@type": "State", name: "Maharashtra" },
        { "@type": "Country", name: "India" },
      ],
      hasOfferCatalog: {
        "@type": "OfferCatalog",
        name: "CA Services",
        itemListElement: [
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Income Tax (ITR) Filing" } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "GST Registration & Compliance" } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Company Registration" } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Statutory Audit" } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "TDS Filing" } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "NRI Taxation" } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "ROC Compliance" } },
          { "@type": "Offer", itemOffered: { "@type": "Service", name: "Bookkeeping & Accounting" } },
        ],
      },
      sameAs: [
        "https://www.linkedin.com/in/ca-raees-kadiwal-28737835/",
      ],
      priceRange: "₹₹",
      currenciesAccepted: "INR",
      paymentAccepted: "Cash, Bank Transfer, UPI",
    },
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: SITE_NAME,
      description: DESCRIPTION,
      publisher: { "@id": `${SITE_URL}/#business` },
      inLanguage: "en-IN",
      potentialAction: {
        "@type": "SearchAction",
        target: {
          "@type": "EntryPoint",
          urlTemplate: `${SITE_URL}/?s={search_term_string}`,
        },
        "query-input": "required name=search_term_string",
      },
    },
    {
      "@type": "BreadcrumbList",
      "@id": `${SITE_URL}/#breadcrumb`,
      itemListElement: [
        {
          "@type": "ListItem",
          position: 1,
          name: "Home",
          item: SITE_URL,
        },
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en-IN"
      className={`${hanken.variable} ${fraunces.variable} h-full antialiased`}
    >
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />

        {/* Theme */}
        <meta name="theme-color" content="#1F2430" />

        {/* Geo targeting */}
        <meta name="geo.region" content="IN-MH" />
        <meta name="geo.placename" content="Malad East, Mumbai" />
        <meta name="geo.position" content="19.1791743;72.8616513" />
        <meta name="ICBM" content="19.1791743, 72.8616513" />

        {/* Structured data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="min-h-full flex flex-col bg-background text-foreground overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
